### ISSUE TITLE
Error when I loaded your model

### ISSUE THREAD

**Issue by wujy2015** [xy0806/miccai17-mmwhs-hybrid#4]
Hi Xin,
Thanks for sharing your code. Are the best model parameters included in model/C3D_unet_1chn/ ? I want to use your model to make a prediction.

I change the function:
def load_chkpoint(self, checkpoint_dir):
        self.saver = tf.train.import_meta_graph('../outcome/model/C3D_unet_1chn/C3DCONV1CHAN.meta')
        self.saver.restore(self.sess, checkpoint_dir)

When I load the model, I got the error:
python main.py 
[{'save_intval': 2000, 'rename_map': '0, 205, 420, 500, 550, 600, 820, 850', 'inputI_size': 96, 'learning_rate': 0.001, 'batch_size': 1, 'inputI_chn': 1, 'output_chn': 8, 'phase': 'test', 'traindata_dir': '/home/ec2-user/ct_test1', 'outputI_size': 96, 'model_name': 'ds_ft_hybrid_4ct.model', 'epoch': 34000, 'testdata_dir': '/home/ec2-user/ct_test1', 'beta1': 0.5, 'ovlp_ita': 4, 'chkpoint_dir': '/home/ec2-user/miccai17-mmwhs-hybrid/ds_ft_hybrid_4ct/outcome/model/C3D_unet_1chn/C3DCONV1CHAN', 'labeling_dir': '/home/ec2-user/ct_test1', 'resize_r': 0.6}]
====== Phase >>> test <<< ======
2018-02-08 08:02:23.175741: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-02-08 08:02:23.257036: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:892] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-02-08 08:02:23.257377: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: 
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
pciBusID: 0000:00:1e.0
totalMemory: 11.17GiB freeMemory: 11.10GiB
2018-02-08 08:02:23.257407: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: Tesla K80, pci bus id: 0000:00:1e.0, compute capability: 3.7)
2018-02-08 08:02:25.762594: W tensorflow/core/framework/op_kernel.cc:1192] Not found: /home/ec2-user/miccai17-mmwhs-hybrid/ds_ft_hybrid_4ct/outcome/model/C3D_unet_1chn/C3DCONV1CHAN.data-00000-of-00001; No such file or directory
2018-02-08 08:02:25.762720: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key pred_prob/kernel not found in checkpoint
2018-02-08 08:02:25.762924: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key aux0_conv/bias not found in checkpoint
2018-02-08 08:02:25.763397: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key aux0_conv/kernel not found in checkpoint
2018-02-08 08:02:25.763826: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key pred_prob/bias not found in checkpoint
2018-02-08 08:02:25.764240: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key conv2_batch_norm/beta not found in checkpoint
2018-02-08 08:02:25.764339: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key deconv4_2/conv/kernel not found in checkpoint
2018-02-08 08:02:25.764640: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key conv1_batch_norm/moving_variance not found in checkpoint
2018-02-08 08:02:25.764715: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key aux0_deconv_1/filter not found in checkpoint
2018-02-08 08:02:25.764783: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key conv2_batch_norm/gamma not found in checkpoint
2018-02-08 08:02:25.765047: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key deconv4_2/batch_norm/moving_variance not found in checkpoint
2018-02-08 08:02:25.765289: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key aux0_prob/filter not found in checkpoint
2018-02-08 08:02:25.765529: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key conv1_batch_norm/moving_mean not found in checkpoint
2018-02-08 08:02:25.765570: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key aux0_deconv_2/filter not found in checkpoint
2018-02-08 08:02:25.765815: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key deconv4_2/batch_norm/moving_mean not found in checkpoint
2018-02-08 08:02:25.766113: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key aux1_conv/bias not found in checkpoint
2018-02-08 08:02:25.766264: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key conv1_batch_norm/gamma not found in checkpoint
2018-02-08 08:02:25.766404: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key conv2_batch_norm/moving_mean not found in checkpoint
2018-02-08 08:02:25.766477: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key deconv4_2/batch_norm/gamma not found in checkpoint
2018-02-08 08:02:25.766771: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key aux1_conv/kernel not found in checkpoint
2018-02-08 08:02:25.766872: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key conv1_batch_norm/beta not found in checkpoint
2018-02-08 08:02:25.767161: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key deconv4_2/batch_norm/beta not found in checkpoint
2018-02-08 08:02:25.767378: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key aux1_deconv_1/filter not found in checkpoint
2018-02-08 08:02:25.767378: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key conv2_batch_norm/moving_variance not found in checkpoint
2018-02-08 08:02:25.767586: W tensorflow/core/framework/op_kernel.cc:1192] Not found: /home/ec2-user/miccai17-mmwhs-hybrid/ds_ft_hybrid_4ct/outcome/model/C3D_unet_1chn/C3DCONV1CHAN.data-00000-of-00001; No such file or directory
2018-02-08 08:02:25.767869: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key deconv4_1/deconv/filter not found in checkpoint
2018-02-08 08:02:25.768083: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key aux2_prob/filter not found in checkpoint
2018-02-08 08:02:25.768154: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key conv3_1_batch_norm/beta not found in checkpoint
2018-02-08 08:02:25.768392: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key aux1_prob/filter not found in checkpoint
2018-02-08 08:02:25.768679: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key aux2_conv/kernel not found in checkpoint
2018-02-08 08:02:25.768728: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key aux2_conv/bias not found in checkpoint
2018-02-08 08:02:25.768882: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key deconv4_1/batch_norm/moving_variance not found in checkpoint
2018-02-08 08:02:25.769093: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key conv3_1_batch_norm/gamma not found in checkpoint
2018-02-08 08:02:25.769325: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key conv3_1_batch_norm/moving_mean not found in checkpoint
2018-02-08 08:02:25.769521: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key conv3_2_batch_norm/beta not found in checkpoint
2018-02-08 08:02:25.769593: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key conv3_1_batch_norm/moving_variance not found in checkpoint
2018-02-08 08:02:25.769849: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key deconv4_1/batch_norm/moving_mean not found in checkpoint
2018-02-08 08:02:25.770033: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key conv3_2_batch_norm/gamma not found in checkpoint
2018-02-08 08:02:25.770123: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key conv3_2_batch_norm/moving_mean not found in checkpoint
2018-02-08 08:02:25.770302: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key conv3_2_batch_norm/moving_variance not found in checkpoint
2018-02-08 08:02:25.770397: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key deconv4_1/batch_norm/gamma not found in checkpoint
2018-02-08 08:02:25.772371: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key deconv4_1/batch_norm/beta not found in checkpoint
2018-02-08 08:02:25.772688: W tensorflow/core/framework/op_kernel.cc:1192] Not found: /home/ec2-user/miccai17-mmwhs-hybrid/ds_ft_hybrid_4ct/outcome/model/C3D_unet_1chn/C3DCONV1CHAN.data-00000-of-00001; No such file or directory
2018-02-08 08:02:25.772950: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key conv4_1_batch_norm/beta not found in checkpoint
2018-02-08 08:02:25.773346: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key conv4_1_batch_norm/moving_mean not found in checkpoint
2018-02-08 08:02:25.773724: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key conv4_1_batch_norm/moving_variance not found in checkpoint
2018-02-08 08:02:25.774095: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key conv4_2_batch_norm/beta not found in checkpoint
2018-02-08 08:02:25.774473: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key conv4_2_batch_norm/gamma not found in checkpoint
2018-02-08 08:02:25.774840: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key conv4_2_batch_norm/moving_mean not found in checkpoint
2018-02-08 08:02:25.775213: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key conv4_2_batch_norm/moving_variance not found in checkpoint
2018-02-08 08:02:25.776569: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key deconv3_2/conv/kernel not found in checkpoint
2018-02-08 08:02:25.776901: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key conv4_1_batch_norm/gamma not found in checkpoint
2018-02-08 08:02:25.777139: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key deconv3_2/batch_norm/moving_variance not found in checkpoint
2018-02-08 08:02:25.777553: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key deconv3_2/batch_norm/moving_mean not found in checkpoint
2018-02-08 08:02:25.777936: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key deconv3_2/batch_norm/gamma not found in checkpoint
2018-02-08 08:02:25.778324: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key deconv3_2/batch_norm/beta not found in checkpoint
2018-02-08 08:02:25.778707: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key deconv3_1/deconv/filter not found in checkpoint
2018-02-08 08:02:25.779088: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key deconv3_1/batch_norm/moving_variance not found in checkpoint
2018-02-08 08:02:25.779480: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key deconv3_1/batch_norm/moving_mean not found in checkpoint
2018-02-08 08:02:25.779863: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key deconv3_1/batch_norm/gamma not found in checkpoint
2018-02-08 08:02:25.780241: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key deconv3_1/batch_norm/beta not found in checkpoint
2018-02-08 08:02:25.780502: W tensorflow/core/framework/op_kernel.cc:1192] Not found: /home/ec2-user/miccai17-mmwhs-hybrid/ds_ft_hybrid_4ct/outcome/model/C3D_unet_1chn/C3DCONV1CHAN.data-00000-of-00001; No such file or directory
2018-02-08 08:02:25.780675: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key deconv2_2/conv/kernel not found in checkpoint
2018-02-08 08:02:25.781083: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key deconv2_2/batch_norm/moving_variance not found in checkpoint
2018-02-08 08:02:25.781469: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key deconv2_2/batch_norm/moving_mean not found in checkpoint
2018-02-08 08:02:25.781863: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key deconv2_2/batch_norm/gamma not found in checkpoint
2018-02-08 08:02:25.782251: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key deconv2_2/batch_norm/beta not found in checkpoint
2018-02-08 08:02:25.782637: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key deconv2_1/deconv/filter not found in checkpoint
2018-02-08 08:02:25.783028: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key deconv2_1/batch_norm/moving_variance not found in checkpoint
2018-02-08 08:02:25.783416: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key deconv2_1/batch_norm/moving_mean not found in checkpoint
2018-02-08 08:02:25.783808: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key deconv2_1/batch_norm/gamma not found in checkpoint
2018-02-08 08:02:25.784207: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key deconv2_1/batch_norm/beta not found in checkpoint
2018-02-08 08:02:25.784285: W tensorflow/core/framework/op_kernel.cc:1192] Not found: /home/ec2-user/miccai17-mmwhs-hybrid/ds_ft_hybrid_4ct/outcome/model/C3D_unet_1chn/C3DCONV1CHAN.data-00000-of-00001; No such file or directory
2018-02-08 08:02:25.784702: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key deconv1_2/conv/kernel not found in checkpoint
2018-02-08 08:02:25.784908: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key conv5_1/batch_norm/beta not found in checkpoint
2018-02-08 08:02:25.797259: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key conv5_1/batch_norm/gamma not found in checkpoint
2018-02-08 08:02:25.797436: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key deconv1_2/batch_norm/moving_variance not found in checkpoint
2018-02-08 08:02:25.797695: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key conv5_1/batch_norm/moving_mean not found in checkpoint
2018-02-08 08:02:25.797976: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key conv5_1/batch_norm/moving_variance not found in checkpoint
2018-02-08 08:02:25.798232: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key conv5_1/conv/kernel not found in checkpoint
2018-02-08 08:02:25.798302: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key deconv1_2/batch_norm/moving_mean not found in checkpoint
2018-02-08 08:02:25.798664: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key conv5_2/batch_norm/gamma not found in checkpoint
2018-02-08 08:02:25.798879: W tensorflow/core/framework/op_kernel.cc:1192] Not found: /home/ec2-user/miccai17-mmwhs-hybrid/ds_ft_hybrid_4ct/outcome/model/C3D_unet_1chn/C3DCONV1CHAN.data-00000-of-00001; No such file or directory
2018-02-08 08:02:25.798950: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key deconv1_2/batch_norm/gamma not found in checkpoint
2018-02-08 08:02:25.799164: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key conv5_2/batch_norm/beta not found in checkpoint
2018-02-08 08:02:25.799297: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key conv5_2/batch_norm/moving_mean not found in checkpoint
2018-02-08 08:02:25.799389: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key conv5_2/batch_norm/moving_variance not found in checkpoint
2018-02-08 08:02:25.799752: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key deconv1_2/batch_norm/beta not found in checkpoint
2018-02-08 08:02:25.799854: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key deconv1_1/batch_norm/beta not found in checkpoint
2018-02-08 08:02:25.800015: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key conv5_2/conv/kernel not found in checkpoint
2018-02-08 08:02:25.800073: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key deconv1_1/batch_norm/gamma not found in checkpoint
2018-02-08 08:02:25.800526: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key deconv1_1/batch_norm/moving_mean not found in checkpoint
2018-02-08 08:02:25.800602: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key deconv1_1/deconv/filter not found in checkpoint
2018-02-08 08:02:25.800771: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key deconv1_1/batch_norm/moving_variance not found in checkpoint
Traceback (most recent call last):
  File "main.py", line 39, in <module>
    tf.app.run()
  File "/home/ec2-user/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "main.py", line 34, in main
    model.test_generate_map()
  File "/home/ec2-user/miccai17-mmwhs-hybrid/ds_ft_hybrid_4ct/src/model.py", line 434, in test_generate_map
    if self.load_chkpoint(self.chkpoint_dir):
  File "/home/ec2-user/miccai17-mmwhs-hybrid/ds_ft_hybrid_4ct/src/model.py", line 517, in load_chkpoint
    self.saver.restore(self.sess, checkpoint_dir)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1666, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/ec2-user/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: /home/ec2-user/miccai17-mmwhs-hybrid/ds_ft_hybrid_4ct/outcome/model/C3D_unet_1chn/C3DCONV1CHAN.data-00000-of-00001; No such file or directory
	 [[Node: save/RestoreV2_17 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_17/tensor_names, save/RestoreV2_17/shape_and_slices)]]
	 [[Node: save/RestoreV2_51/_117 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_362_save/RestoreV2_51", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

Caused by op u'save/RestoreV2_17', defined at:
  File "main.py", line 39, in <module>
    tf.app.run()
  File "/home/ec2-user/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "main.py", line 28, in main
    model = unet_3D_xy(sess, param_set)
  File "/home/ec2-user/miccai17-mmwhs-hybrid/ds_ft_hybrid_4ct/src/model.py", line 36, in __init__
    self.build_model()
  File "/home/ec2-user/miccai17-mmwhs-hybrid/ds_ft_hybrid_4ct/src/model.py", line 116, in build_model
    self.saver = tf.train.Saver()
  File "/home/ec2-user/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1218, in __init__
    self.build()
  File "/home/ec2-user/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1227, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1263, in _build
    build_save=build_save, build_restore=build_restore)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 751, in _build_internal
    restore_sequentially, reshape)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 427, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 267, in restore_op
    [spec.tensor.dtype])[0])
  File "/home/ec2-user/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1021, in restore_v2
    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

NotFoundError (see above for traceback): /home/ec2-user/miccai17-mmwhs-hybrid/ds_ft_hybrid_4ct/outcome/model/C3D_unet_1chn/C3DCONV1CHAN.data-00000-of-00001; No such file or directory
	 [[Node: save/RestoreV2_17 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_17/tensor_names, save/RestoreV2_17/shape_and_slices)]]
	 [[Node: save/RestoreV2_51/_117 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_362_save/RestoreV2_51", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

**Comment by xy0806** [comment]
Dear Wu,

The C3D is just for transfer learning. It's not the best model.
I will upload the C3D and a trained model soon. Please check back 2~3 days later.

best,
xin

**Comment by xy0806** [comment]
Dear Junyan,

you can find the required model below:

C3D Model:
https://drive.google.com/open?id=1N4LVb03Ehot34Bxcm1KkO14csuThOXUv

Trained model for CT segmentation:
https://drive.google.com/open?id=1Nly8ghHvedVC3EZetFJRRtLq7Ll-U0Fx

A CT data from the training dataset for demo:
https://drive.google.com/open?id=1b2sFaKrBfTRx6i0lBD5L6IZXP01W9L5C

best,
xin

**Comment by wujy2015** [comment]
Thank you so much

**Comment by ZHANGHUAHAI** [comment]
I have encountered the same problem, how did you solve it?

**Comment by xy0806** [comment]
dear zhang,

you can find the model from the links in the Readme.

best,
xin

**Comment by ZHANGHUAHAI** [comment]
Hi xin
I downloaded the model and this problem occurred:
====== Phase >>> train <<< ======
2018-08-28 21:43:57.050157: I T:\src\github\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
 [*] Reading checkpoint...
 [*] Load SUCCESS
Traceback (most recent call last):
  File "main.py", line 38, in <module>
    tf.app.run()
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "main.py", line 30, in main
    model.train()
  File "D:\miccai17-mmwhs-hybrid-master\ds_ft_hybrid_4ct\src\model.py", line 237, in train
    batch_img, batch_label = get_batch_patches(img_clec, label_clec, self.inputI_size, self.batch_size, chn=1, flip_flag=True, rot_flag=True)
  File "D:\miccai17-mmwhs-hybrid-master\ds_ft_hybrid_4ct\src\utils.py", line 57, in get_batch_patches
    rand_img = img_clec[rand_idx[0]]
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by xy0806** [comment]
hi,

I think you basically need to debug you code, it seems like the code can
not find your dataset folders. And thus, the img_clec and label_clec are
empty.

best,
xin

**Comment by JohnleeHIT** [comment]
> 
> 
> Dear Junyan,
> 
> you can find the required model below:
> 
> C3D Model:
> https://drive.google.com/open?id=1N4LVb03Ehot34Bxcm1KkO14csuThOXUv
> 
> Trained model for CT segmentation:
> https://drive.google.com/open?id=1Nly8ghHvedVC3EZetFJRRtLq7Ll-U0Fx
> 
> A CT data from the training dataset for demo:
> https://drive.google.com/open?id=1b2sFaKrBfTRx6i0lBD5L6IZXP01W9L5C
> 
> best,
> xin

Would i get the same validation result with the "trained model for CT segmentation" as you described in the paper ? Thanks
